export const ALERT_SUCCESS_MESSAGE = 'ALERT_SUCCESS_MESSAGE';
export const ALERT_WARNING_MESSAGE = 'ALERT_WARNING_MESSAGE';
export const ALERT_ERROR_MESSAGE = 'ALERT_ERROR_MESSAGE';
export const ALERT_INFO_MESSAGE = 'ALERT_INFO_MESSAGE';
export const ALERT_SNACKBAR_OPEN = 'ALERT_SNACKBAR_OPEN';
export const ALERT_SNACKBAR_CLOSE = 'ALERT_SNACKBAR_CLOSE';
