export const GET_ALL_DEVELOPERS = 'GET_ALL_DEVELOPERS';
export const GET_ALL_DEVELOPERS_FAILED = 'GET_ALL_DEVELOPERS_FAILED';
export const GET_ALL_CHATS_USER_WISE = 'GET_ALL_CHATS_USER_WISE'
export const GET_CURRENT_CHAT_USER_WISE = 'GET_CURRENT_CHAT_USER_WISE';
export const GET_ALL_CHATS_USER_WISE_FAILED = 'GET_ALL_CHATS_USER_WISE_FAILED';
export const GET_ALL_INVESTORS = 'GET_ALL_INVESTORS';